### ISSUE TITLE
Why do i receive multi account request error? I do have multiple accounts, im aware.what do i need to change in the code?

### ISSUE THREAD

**Issue by JH2392** [selesnow/rgoogleads#10]
Authentication complete.
```
> ad_group_report <- gads_get_report(
+   resource    = "ad_group",
+   fields      = c("ad_group.campaign",
+                   "ad_group.id",
+                   "ad_group.name",
+                   "ad_group.status",
+                   "metrics.clicks",
+                   "metrics.cost_micros"),
+   date_from   = "2021-01-08",
+   date_to     = "2021-01-10",
+   where       = "ad_group.status = 'ENABLED'",
+   order_by    = c("metrics.clicks DESC", "metrics.cost_micros")
+ )
```
i Multi account request
! The request you sent did not return any results, check the entered parameters and repeat the opposition.

**Comment by selesnow** [comment]
Hi!

1. You start downloading data from several accounts at once, first try to work with one account;
2. Try querying data without applying a filter (dont use `where`);
3. Make sure that the account you are working with has data for the specified period, in your case 2021-01-08 - 2021-01-10, for those ad groups that currently have an active status (ad_group.status = 'ENABLED ')

I think that the problem is in the filter, because. you are requesting data from a year ago, for those ad groups that are now in active status, for sure these ad groups did not exist a year ago

**Comment by selesnow** [comment]
Use next code before loading report:

```r
gads_set_customer_id('xxx-xxx-xxxx')
```

Change `xxx-xxx-xxxx` to your customer account id. Next try to get report:

```r
ad_group_report <- gads_get_report(
   resource    = "ad_group",
   fields      = c("ad_group.campaign",
                   "ad_group.id",
                   "ad_group.name",
                   "ad_group.status",
                   "metrics.clicks",
                   "metrics.cost_micros"),
   date_from   = "2021-01-08",
   date_to     = "2021-01-10"
)
```

**Comment by JH2392** [comment]
When i do this, i get the error 
```
Error in names(message) <- `*vtmp*` : 
  'names' attribute [1] must be the same length as the vector [0]
```

**Comment by JH2392** [comment]
Hi @selesnow, this is finally working when i do gads_set_customer_id('xxx-xxx-xxxx'), but is there a way for me to get multi account data at once? because I have 2 customer id under one account

**Comment by JH2392** [comment]
Also @selesnow, why cant i use where filter? im noticing when i run this query that it returns the same number of rows irrespective of me changing the dates. is there no way to set adgroup.status enabled?

**Comment by selesnow** [comment]
@JH2392 Hi!

>Hi @selesnow, this is finally working when i do gads_set_customer_id('xxx-xxx-xxxx'), but is there a way for me to get multi account data at once? because I have 2 customer id under one account

Yep, try to use `gads_set_customer_id(c('xxx-xxx-xxxx', 'yyy-yyy-yyyy'))`

>Also @selesnow, why cant i use where filter? im noticing when i run this query that it returns the same number of rows irrespective of me changing the dates. is there no way to set adgroup.status enabled?

When testing, the filters worked out correctly, but keep in mind that they take the current statuses of ad groups, and not the statuses that are relevant for the period you set.
