### ISSUE TITLE
How can I convert this Radwords script into googleads script

### ISSUE THREAD

**Issue by JH2392** [selesnow/rgoogleads#11]
I am trying to migrate to googleads from adwords but the syntax seems really different and is not giving desired output. 

```
```
# LINES BELOW ARE FOR TROUBLESHOOTING AUTHENTICATION
#install.packages("RCurl")
#require(devtools)
#install_github('jburkhardt/RAdwords')

# Credentials set up at https://console.developers.google.com under htxx@gmail.com
# developer.token <-'atGgdxxCPDEzvA'
# client.id <-"38920xx.apps.googleusercontent.com"
# client.secret <-"9Jxxt7a"

google_auth <- doAuth()
refreshToken(google_auth)

options(RCurlOptions = list(cainfo = system.file("CurlSSL", "cacert.pem", package = "RCurl")))

[SelectFields = c('GclId','AdGroupId','CampaignId','CriteriaId','Date')
ReportName = "CLICK_PERFORMANCE_REPORT"

FactAdWordsClickPerformance <- data.frame()

dates <- data.frame(Date = unique(frame$StartDate))

for (i in 1:nrow(dates)) {
  FactAdWordsClickPerformanceLoop <- getAdwordsData(ReportName,SelectFields,dates[i,],dates[i,])
  FactAdWordsClickPerformance <- rbind(FactAdWordsClickPerformance,FactAdWordsClickPerformanceLoop)
}](url)
```

when i run my code, i do not need to login to gmail or verify my id by text code each time i run this script. In googleads each time i run the script even with gargle Oauth, it asks me for verification. What do i need to do to make it run without asking me to verify my identity each time? Also, could you please translate my script into googleads friendly script. i know that the select fields values can be changed using query migration tool. but what else needs to be changed. please translate my code in googleads language

**Comment by selesnow** [comment]
I am not at the PC at the moment,

Try to see https://cran.r-project.org/web/packages/rgoogleads/vignettes/migrate_from_radrowds_us.html

**Comment by selesnow** [comment]
And please read full gargle documents!!!
https://cran.r-project.org/web/packages/gargle/index.html


I already explained to you that Gargle is used for authorization under the hood, read all its documentation.  rgooglelads allows you to configure the authorization configuration through the gads_auth_configurations() function.

**Comment by JH2392** [comment]
It is not working after reading all the documentation. please help convert my code into your googleads script

**Comment by selesnow** [comment]
Unfortunately, I have no way to help you, I recommend that you look for another package to work with Google Ads API.

**Comment by selesnow** [comment]
@JH2392 

Hi, a new package for Google Railways has appeared, maybe there is this functionality [r4googleads](https://github.com/banboo-data/r4googleads)
