### ISSUE TITLE
Error: The caller does not have permission: User doesn't have permission to access customer

### ISSUE THREAD

**Issue by JH2392** [selesnow/rgoogleads#12]
library(rgoogleads)
gads_auth('htxlrxx@gmail.com')
gads_set_customer_id('801-534-xxxx')

ad_group_report <- gads_get_report(
  resource    = "ad_group",
  fields      = c("ad_group.campaign",
                  "ad_group.id",
                  "ad_group.name",
                  "ad_group.ad.final_urls",
                  "ad_group.status",
                  "metrics.clicks",
                  "metrics.cost_micros"),
  date_from   = "2022-02-01",
  date_to     = "2022-02-03"
  #where       = "ad_group.status = 'ENABLED'
)
i Loading data: 801-534-xxxx
i Compose query
i Send request
i Get answer query
Error: The caller does not have permission: User doesn't have permission to access customer. Note: If
you're accessing a client customer, the manager's customer id must be set in the 'login-customer-id'
header. See https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid

Why do I receive this error?

**Comment by selesnow** [comment]
Hi, 

It is most likely that this error is due to the fact that you are working through a manager account, in which case you must first specify the manager account ID (`gads_set_login_customer_id()`), and then the client account (`gads_set_customer_id()`).

```r
# set manager account id (options)
gads_set_login_customer_id('xxx-xxx-xxxx')

# set client account id
gads_set_customer_id('801-534-xxxx')

ad_group_report <- gads_get_report(
resource = "ad_group",
fields = c("ad_group.campaign",
"ad_group.id",
"ad_group.name",
"ad_group.ad.final_urls",
"ad_group.status",
"metrics.clicks",
"metrics.cost_micros"),
date_from = "2022-02-01",
date_to = "2022-02-03"
#where = "ad_group.status = 'ENABLED'"
)
```

**Comment by JH2392** [comment]
where do i find the manager account id?

**Comment by selesnow** [comment]
>where do i find the manager account id?

This question has nothing to do with the `rgoogleads` package. But, you can find it in the same place as the id of a client account, please study the structure of Google Ads, I am very busy solving my own work issues, and do not have time for consultation.

**Comment by selesnow** [comment]
For more details
https://developers.google.com/google-ads/api/docs/migration/login-customer-id
