### ISSUE TITLE
This app is blocked by Google

### ISSUE THREAD

**Issue by ThinkUser** [selesnow/rgoogleads#14]
Hi

I've set up everything in GCS and Ads and while I am trying to auth the account i am getting an error that Google blocked access.

This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.
![Screenshot_2](https://user-images.githubusercontent.com/43462938/157053093-eca3d8cb-f3b2-4557-b1b6-0b95df5cc430.png)

Did I miss something in the auth steps?

Thanks

**Comment by selesnow** [comment]
Hello, 

Can you show me your code for authorizations?

And, you can use default app and developer token for authorizations.

**Comment by ThinkUser** [comment]
Hey
Thank you for the fast comment.

library(rgoogleads)
gads_auth_configure(path = '~/client-id.json')
gads_auth(email = 'erez@company.co.il', developer_token = "XXXXXXmdRnaCCjw")

Then I get a popup on chrome to sign into my account and the message above.

Thanks

**Comment by selesnow** [comment]
Maybe you must add test user in your OAuth app?

Try to see [official documentation of OAuth App Settings](https://developers.google.com/google-ads/api/docs/first-call/oauth-cloud-project).


Default app is verified by Google.

![](http://img.netpeak.ua/alsey/O8B56X.png)

**Comment by selesnow** [comment]
And you can try to use `httr`

```r
app <- httr::oauth_app(appname = "app name", key = "app id", secret = "app secret")
gads_auth_configure(app = app)
```

**Comment by ThinkUser** [comment]
Thanks

I've tried to use the httr option and I get this
_You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules._

Is it something on my end or something with Google verification proccess?

Thanks

![image](https://user-images.githubusercontent.com/43462938/158439241-c6c20207-234f-4401-8ee5-35d5fcfdf09a.png)

**Comment by ThinkUser** [comment]
okay, so a quick update.

its working locally but not on R server I launched

Thanks

**Comment by jthar111** [comment]
@ThinkUser im facing the same issue from R server. did you get it to work there now?

**Comment by jthar111** [comment]
@selesnow im facing the same issue as @ThinkUser . it doesnt work from remote server
 any suggestions?

**Comment by ThinkUser** [comment]
> @ThinkUser im facing the same issue from R server. did you get it to work there now?

Hey
No, didnt find a solution. 
If you do find please share :-)

Its working locally tough... so I am running scheduled scripts on my PC (which is a bit annoying as it has to be turned on)

Thanks
