### ISSUE TITLE
Reports suddenly stopped working

### ISSUE THREAD

**Issue by jasp1994** [selesnow/rgoogleads#18]
My code has been working for months and as of 03.05.22 its stopped working with the following error.

Error in eval(parse(text = text, keep.source = FALSE), envir) : 
  object 'type' not found

I've tried everything I can to debug but can't figure out what the issue is. The logger prints my login_customer_id and then my customer_id then errors. 

I've tested with example code (using my credentials) and the same error occurs.

**Comment by selesnow** [comment]
Hello, this error is related to the `gargle` package, and the `request_retry()` function, most likely a problem with the built-in out OAuth client limit, try creating your own and go through authorization through it.

See https://github.com/selesnow/rgoogleads#use-own-oauth-client

**Comment by jasp1994** [comment]
Thanks for the reply. I tried the other authentication method detailed, but get a refresh token error. (no refresh token stored) is this a gargle error as well?

**Comment by dave-m91** [comment]
I have exacly the same problem. Last week everything worked fine, but today i have the same error as jasp1994. I tried the authorization method with json file and httr::oauth_app function 🤷🏻‍♂️

**Comment by Ferric2004** [comment]
Hi!

I'm tryng the method you detailed

`app <- httr::oauth_app(appname = "app name", key = "app id", secret = "app secret")
gads_auth_configure(app = app)`

but can't get the appname parameter, there's a way to retrieve it?

**Comment by selesnow** [comment]
> Hi!
> 
> I'm tryng the method you detailed
> 
> `app <- httr::oauth_app(appname = "app name", key = "app id", secret = "app secret") gads_auth_configure(app = app)`
> 
> but can't get the appname parameter, there's a way to retrieve it?

you can specify any arbitrary application name

**Comment by selesnow** [comment]
> Thanks for the reply. I tried the other authentication method detailed, but get a refresh token error. (no refresh token stored) is this a gargle error as well?

Yes, authorization process is fully developed based on gargle.

**Comment by jasp1994** [comment]
Authentication is working again!

**Comment by jasp1994** [comment]
Looks like it stopped working again :(
