### ISSUE TITLE
OAuth out-of-band flow

### ISSUE THREAD

**Issue by sshemtov** [selesnow/rgoogleads#19]
Hello,

I'm getting warning from Google that I need to migrate Oath out-of-band flow to an alternative method before Oct 3rd 2022.
https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html

How do you suggest accomplishing this with the rgoogleads package?

Thanks

**Comment by selesnow** [comment]
Hello, 

Do you use own OAuth Client or Default rgoogleads OAuth client for authorization?

1. If you use own client and it client work on test mode, No action is required on your part as apps using OOB in [testing](https://notifications.google.com/g/p/APNL1TixNRSzRhR_0mxb_ajat2Z88g50HZ6Y7nBeAC5IE1M6uMt0Q_7kiT0voXiY3oCa-3S0x6PVjR7fznmR6kO1jprSrUjqpVJxGb8yBfRzm1am47uN2BHO16R0UrK2Ycctif2wDEWn0fAFl9WpJZUSf_Nw000NEiwC) mode will not be affected by this change.
2. If you use default OAuth client, i working around this issue now inside googleads default oauth client.

**Comment by selesnow** [comment]
`rgoogleads` dont use OOB.

No action is required from you.

**Comment by sshemtov** [comment]
Hello,

I use the default as far as I know:

gads_auth_configure(path = 'path-to-json.apps.googleusercontent.com.json')
gads_auth(email = 'my@gmail.com', developer_token = "jdjdjdjdjdjdjdjd")

The email I received from Google said my client ID's will be blocked from using OOB. If rgoogleads doesn't use OOB then perhaps Google is referring to old calls from other packages or elsewhere. I'll check it out.

Thanks!
