### ISSUE TITLE
v9 deprecated

### ISSUE THREAD

**Issue by sshemtov** [selesnow/rgoogleads#22]
Hello,

Is rgoogleads able to use a new version of api? I'm getting an error version v9 is deprecated.

Thanks

**Comment by ReinhardSchmidbauer** [comment]
Hi there,

we're getting the following error:
`Request contains an invalid argument.: Version v9 is deprecated. Requests to this version will be blocked.
`

@sshemtov please help!

Thank you!

**Comment by jthar111** [comment]
@ReinhardSchmidbauer @sshemtov I found a work around to this. Please update the library to the latest version if u are using R

**Comment by sshemtov** [comment]
@ReinhardSchmidbauer that only works intermittently though - already tried that before seeing your response.

We need @selesnow to comment.

**Comment by ReinhardSchmidbauer** [comment]
Thanks for your response @sshemtov ! I am at the latest version 0.8.0.
Once in a while the requests yield a response but most of the time they just get blocked with the error message above.

**Comment by sshemtov** [comment]
Seems to be working better now, I had to upgrade my server where the task was still failing.

**Comment by selesnow** [comment]
Hi all, rgoogleads 0.8.0 use Google Ads API v11.
And you can change API version use `options(gads.api.version = 'v11')`
