### ISSUE TITLE
Auth with service account json file returns User in the cookie is not a valid Ads user

### ISSUE THREAD

**Issue by can-taslicukur** [selesnow/rgoogleads#23]
Hi !

When I authenticate with the service account json file using `gads_auth(path = "json file path")` ,  `gads_get_accessible_customers()` returns "User in the cookie is not a valid Ads
  user" error. However when I use  `gads_get_accessible_customers()` with the normal auth procedure (`gads_auth()`), I am able to successfully get accessible customers.

I am using "SERVICE ACCOUNT JSON FILE PATH" in the example code as a placeholder for the file path in my own code.

```
library(rgoogleads)
gads_auth(path = "SERVICE ACCOUNT JSON FILE PATH")
gads_get_accessible_customers()

# Auto-refreshing stale OAuth token.
# ℹ Get answer query
# Error in `error_message()`:
# ! User in the cookie is not a valid Ads
#  user.
# Run `rlang::last_error()` to see where the error occurred.
```

**Comment by selesnow** [comment]
Hi, i don`t know how use servoce account in Google Ads API. 

Try to see [this](https://developers.google.com/google-ads/api/docs/oauth/service-accounts?hl=en)
