### ISSUE TITLE
Fix date overrides in gads_get_report.R

### ISSUE THREAD

**Issue by sashakrasnikovpdffiller** [selesnow/rgoogleads#9]
В gads_get_report.R есть логика переопределения полей date_from, date_to, during для ресурсов, которые не содержат дат. В переопределении поля during попала опечатка -- поле переопределяется на NA, хотя поле during допускает только строковое значение или NULL.
Из-за этого невозможно выгружать данные по ресурсам типа label, даже если явно передавать during = NULL -- это поле всегда будет переопределяться на NA.
```
! fields values of date_from, date_to and during was unset automatically, because it is not selectable with label
---------------------------
Error in match.arg(during) : ‘arg’ must be NULL or a character vector

```
TODO: заменить переопределение на during <- NULL

**Comment by selesnow** [comment]
Приветствую, благодарю за информацию, уже внёс изменения, можете установить свежую версию `0.4.1.9000` с GitHub.
